import test from "node:test";
import assert from "node:assert/strict";
import { createNewsArticle } from "../server/news/model.js";
import { validateNewsArticle, isSafeNewsUrl, sanitizeNewsText } from "../server/news/validation.js";
import { normaliseNewsArticle, deduplicateArticles, mapCategory } from "../server/news/normalizers.js";
import { NewsCache } from "../server/news/cache.js";
import { MockNewsDataProvider } from "../server/news/mock-provider.js";
import { LiveNewsDataProvider } from "../server/news/provider.js";
import { clusterStories, relatedNews } from "../server/news/clustering.js";
import { classifyBreaking, rankTopStories } from "../server/news/ranking.js";
import { templateSummary, templateInterpretation, mapAffectedAssets, buildMarketSentiment, newsRisk } from "../server/news/intelligence.js";
import { scannerNewsRiskContext, aiAnalysisNewsContext, tradePlannerNewsRisk, askJarvisNewsHandoff } from "../server/news/integrations.js";
import { NewsEngine } from "../server/news/service.js";
import { handleNewsApiRequest } from "../server/news/router.js";
const demo = async () => (await new MockNewsDataProvider().getArticles())[0];

test("article model preserves missing fields", () => { const article = createNewsArticle({ id: "x", headline: "Demo" }); assert.equal(article.articleUrl, null); assert.deepEqual(article.entities, []); });
test("mock article validates and is safely normalized", async () => { const article = await demo(); assert.deepEqual(validateNewsArticle(article).errors, []); assert.equal(article.dataStatus, "demo"); assert.equal(article.verificationStatus, "demo"); });
test("headline/source/timestamp validation rejects malformed article", async () => { const article = { ...(await demo()), headline: "", sourceName: null, publishedAt: "invalid" }; assert.equal(validateNewsArticle(article).valid, false); });
test("category mapping is allowlisted", () => { assert.equal(mapCategory("Central Banks"), "central_banks"); assert.equal(mapCategory("unknown-provider-value"), "other"); });
test("URL validation and HTML sanitisation are safe", () => { assert.equal(isSafeNewsUrl("javascript:alert(1)"), false); assert.equal(sanitizeNewsText("<script>x</script>Hello"), "xHello"); });
test("normaliser rejects unsafe URL", async () => { const article = await demo(); assert.throws(() => normaliseNewsArticle({ ...article, articleUrl: "javascript:alert(1)" }), { code: "INVALID_PROVIDER_RESPONSE" }); });
test("deduplication keeps one canonical article", async () => { const article = await demo(); assert.equal(deduplicateArticles([article, { ...article }]).length, 1); });
test("story clustering groups shared entities", async () => { const article = await demo(); const clusters = clusterStories([article, { ...article, id: "second", sourceName: "Second Demo Source" }]); assert.equal(clusters.length, 1); assert.equal(clusters[0].articleIds.length, 2); });
test("fixed demo stories are never breaking", async () => { assert.equal(classifyBreaking({ ...(await demo()), isBreaking: true }), false); });
test("top story ranking is deterministic", async () => { const articles = await new MockNewsDataProvider().getArticles(); assert.equal(rankTopStories(articles)[0].impact, "high"); });
test("summary and interpretation use available source fields", async () => { const article = await demo(); assert.match(templateSummary(article)[0], /demonstration/i); assert.equal(templateInterpretation(article).confirmationRequired, true); });
test("asset mapping and related news are conservative", async () => { const articles = await new MockNewsDataProvider().getArticles(); assert.ok(mapAffectedAssets(articles[0]).some((item) => item.asset === "XAUUSD")); assert.equal(relatedNews(articles[0], articles).length, 1); });
test("demo sentiment and risk never appear verified or clear", async () => { const article = await demo(); assert.equal(buildMarketSentiment(article).riskSentiment, "insufficient_data"); assert.equal(newsRisk(article).scannerScore, 0); });
test("cache stores and deduplicates requests", async () => { const cache = new NewsCache(); let calls = 0; const load = async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 5)); return [await demo()]; }; const [a, b] = await Promise.all([cache.dedupe("x", load), cache.dedupe("x", load)]); assert.equal(calls, 1); cache.set("x", a, 1000); assert.deepEqual(cache.get("x"), b); });
test("mock and live provider statuses are honest", async () => { const mock = new MockNewsDataProvider(); assert.equal(mock.getProviderStatus().status, "demo"); const live = new LiveNewsDataProvider(); assert.equal(live.getProviderStatus().status, "disconnected"); await assert.rejects(live.getArticles(), { code: "NEWS_DATA_NOT_CONFIGURED" }); });
test("integration points preserve unavailable production risk", async () => { const articles = await new MockNewsDataProvider().getArticles(); assert.equal(scannerNewsRiskContext(articles, "XAUUSD").score, 0); assert.equal(tradePlannerNewsRisk(articles, "XAUUSD").status, "Demo"); assert.equal(aiAnalysisNewsContext(articles, "XAUUSD").verificationStatus, "demo"); assert.equal(askJarvisNewsHandoff(articles[0]).decisionStatus, "Preliminary"); });
test("engine filters and summary use provider results", async () => { const engine = new NewsEngine({ env: { NEWS_DATA_MODE: "mock" } }); assert.equal((await engine.getArticles({ category: "crypto" })).articles.length, 1); const summary = await engine.getSummary(); assert.equal(summary.dataStatus, "demo"); assert.equal(summary.breakingNewsCount, 0); });
test("news API routes return stable Demo envelopes", async () => { for (const path of ["/api/news/status", "/api/news/articles", "/api/news/top-stories", "/api/news/breaking", "/api/news/summary", "/api/news/articles/demo-policy-guidance"]) { const response = await handleNewsApiRequest(new Request(`https://jarvis.test${path}`), { NEWS_DATA_MODE: "mock" }); assert.equal(response.status, 200); const body = await response.json(); assert.equal(body.success, true); assert.equal(body.meta.dataStatus, "demo"); } });
test("article-not-found and live-not-configured states are safe", async () => { const missing = await handleNewsApiRequest(new Request("https://jarvis.test/api/news/articles/missing"), { NEWS_DATA_MODE: "mock" }); assert.equal(missing.status, 404); const live = await handleNewsApiRequest(new Request("https://jarvis.test/api/news/articles"), { NEWS_DATA_MODE: "live" }); assert.equal(live.status, 503); assert.equal((await live.json()).error.code, "NEWS_DATA_NOT_CONFIGURED"); });
